networks:
  shared_network:
    external: true

services:
  private-file-manager:
    image: yongyuanfan/workerman-php:8.4.4
    container_name: private-file-manager
    restart: unless-stopped
    ports:
      - "8787:8787"
    volumes:
      - .:/app
    networks:
      - shared_network
    command: ["/bin/sh", "/app/private-file-manager"]
