networks:
  private_file_manager_network:
    driver: bridge

services:
  private-file-manager:
    build: .
    container_name: private-file-manager
    restart: unless-stopped
    ports:
      - "8787:8787"
    volumes:
      - ./bin/php:/usr/local/bin/php
      - ./bin/composer:/usr/local/bin/composer
      - .:/app
      - ./storage:/app/storage
    networks:
      - private_file_manager_network
