networks:
  private-file-manager-network:
    driver: bridge

services:
  private-file-manager:
    image: yongyuanfan/workerman-php:8.4.4
    container_name: private-file-manager
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - "8787:8787"
    command: ["/bin/sh", "/app/private-file-manager"]
    depends_on:
       - mysql
       - redis
    networks:
      - private-file-manager-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "private-file-manager"
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - private-file-manager-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - private-file-manager-network

volumes:
  mysql_data:
  redis_data:
